from __future__ import annotations

# Compatibility facade: keep existing imports stable while state responsibilities
# live in smaller service modules.
from soul.services.state_core.knowledge import (
    contains_durable_signal,
    dedupe_preserve_order,
    durable_sentences,
    infer_priority,
    infer_state_kind,
    knowledge_points_from_evidence,
    normalize_knowledge_point,
    stable_state_item_id,
    why_remember_for_statement,
)
from soul.services.state_core.proposals import (
    add_state_item_operation,
    append_patch_status,
    apply_patch_proposal,
    edit_patch_proposal,
    explicit_operations_from_evidence,
    operations_for_apply,
    operations_from_knowledge_points,
    proposal_refs_from_evidence,
    proposal_title_from_evidence,
    propose_patch,
    recommend_patch_review,
    state_item_operation_from_payload,
    why_remember_from_evidence,
)
from soul.services.state_core.state_projection import (
    is_state_item_active,
    project_state_items,
    projection_sort_key,
    state_item_matches_task,
)
from soul.services.state_core.state_render import (
    accepted_state_items_for_injection,
    format_accepted_state_injection,
    format_items,
    format_projected_state_context,
    format_state_context,
    format_state_items,
    is_injectable_accepted_state_item,
)
from soul.services.state_core.state_store import (
    DEFAULT_PATCH_LOG_NAME,
    DEFAULT_STATE_MARKDOWN_NAME,
    DEFAULT_STATE_NAME,
    StatePaths,
    append_patch_proposal,
    brain_dir,
    find_patch_proposal,
    initial_state,
    int_value,
    load_patch_proposals,
    load_state,
    load_state_markdown,
    save_state,
    state_paths,
    utc_now,
)

__all__ = [
    "DEFAULT_PATCH_LOG_NAME",
    "DEFAULT_STATE_MARKDOWN_NAME",
    "DEFAULT_STATE_NAME",
    "StatePaths",
    "add_state_item_operation",
    "append_patch_proposal",
    "append_patch_status",
    "apply_patch_proposal",
    "brain_dir",
    "contains_durable_signal",
    "dedupe_preserve_order",
    "durable_sentences",
    "edit_patch_proposal",
    "explicit_operations_from_evidence",
    "find_patch_proposal",
    "accepted_state_items_for_injection",
    "format_accepted_state_injection",
    "format_items",
    "format_projected_state_context",
    "format_state_context",
    "format_state_items",
    "infer_priority",
    "infer_state_kind",
    "initial_state",
    "int_value",
    "is_injectable_accepted_state_item",
    "is_state_item_active",
    "knowledge_points_from_evidence",
    "load_patch_proposals",
    "load_state",
    "load_state_markdown",
    "normalize_knowledge_point",
    "operations_for_apply",
    "operations_from_knowledge_points",
    "project_state_items",
    "projection_sort_key",
    "proposal_refs_from_evidence",
    "proposal_title_from_evidence",
    "propose_patch",
    "recommend_patch_review",
    "save_state",
    "stable_state_item_id",
    "state_item_matches_task",
    "state_item_operation_from_payload",
    "state_paths",
    "utc_now",
    "why_remember_for_statement",
    "why_remember_from_evidence",
]
