from __future__ import annotations


DEFAULT_WORKING_EXPIRY = "end_of_day"
DEFAULT_WORKING_REVIEW_AFTER = "end_of_day"

WORKING_STATEMENT_MAX_LENGTH = 320
WORKING_REASON_MAX_LENGTH = 240
WORKING_SCOPE_MAX_LENGTH = 120

WORKING_TOKEN_MIN_LENGTH = 4

CONFLICT_NEGATION_SIGNALS = (
    "不再",
    "do not",
    "don't",
)
