from __future__ import annotations

from typing import Any, Protocol


class BackgroundService(Protocol):
    def install(self, *, interval_seconds: float, load: bool = True) -> dict[str, Any]: ...

    def start(self) -> dict[str, Any]: ...

    def stop(self) -> dict[str, Any]: ...

    def restart(self) -> dict[str, Any]: ...

    def uninstall(self) -> dict[str, Any]: ...

    def status(self) -> dict[str, Any]: ...
